getAllProductsBaseUri=https://automationexercise.com/
getAllProductsEndPoint=api/productsList
searchProductsEndPoint=api/searchProduct
reqResBaseUri=https://reqres.in/
getAllUsersEndPoint=api/users
createUserEndPoint=/api/users
token.endpoint=https://reqres.in/api/login

executionType=api
basic.username=admin
basic.password=admin123
api.key=abcd1234